apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: kevinp7781/nodejs
    ports:
    - name: nodejs-port
      containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 15
      timeoutSeconds: 30
    readinessProbe:
      httpGet:
        path: /
        port: nodejs-port
      initialDelaySeconds: 15
      timeoutSeconds: 30
